[package]
name = "iyon"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "iyon"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
crossterm.workspace = true
ratatui.workspace = true
rayon.workspace = true
serde.workspace = true
tokio.workspace = true
toml.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
iyon-api.workspace = true
iyon-core.workspace = true
iyon-tui.workspace = true
textwrap = "0.16.2"
