use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use crate::binding::{BindingRecord, Strategy, load_mapping_dir, validate_manifest_mappings};
use crate::error::ApiSurfaceError;
use crate::model::{ApiKind, ApiManifest};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedSdk {
    pub modules: BTreeMap<String, String>,
}

pub fn generate(
    manifest: &ApiManifest,
    mapping_dir: &Path,
) -> Result<GeneratedSdk, ApiSurfaceError> {
    let mappings = load_mapping_dir(mapping_dir)?;
    let summary = validate_manifest_mappings(manifest, &mappings)?;
    if !summary.missing.is_empty() || !summary.stale.is_empty() {
        return Err(ApiSurfaceError::configuration(
            format!(
                "cannot generate SDK with mapping drift: missing={}, stale={}",
                summary.missing.len(),
                summary.stale.len()
            ),
            Some(mapping_dir.display().to_string()),
        ));
    }
    let kinds = item_kinds(manifest);
    let mut grouped = BTreeMap::<String, Vec<&BindingRecord>>::new();
    for record in &summary.records {
        grouped
            .entry(record.typescript_module.clone())
            .or_default()
            .push(record);
    }
    let mut modules = BTreeMap::new();
    for (module, mut records) in grouped {
        records.sort_by(|left, right| left.typescript_export.cmp(&right.typescript_export));
        modules.insert(module.clone(), render_module(&module, records, &kinds));
    }
    modules.insert("iyon:plugins".into(), plugins_stub());
    Ok(GeneratedSdk { modules })
}

pub fn write_sdk(
    manifest: &ApiManifest,
    mapping_dir: &Path,
    output_dir: &Path,
) -> Result<(), ApiSurfaceError> {
    let sdk = generate(manifest, mapping_dir)?;
    std::fs::create_dir_all(output_dir).map_err(|error| {
        ApiSurfaceError::configuration(
            format!("cannot create SDK output directory: {error}"),
            Some(output_dir.display().to_string()),
        )
    })?;
    for (module, source) in sdk.modules {
        let name = module.replace(':', "-");
        let path = output_dir.join(format!("{name}.d.ts"));
        std::fs::write(path, source).map_err(|error| {
            ApiSurfaceError::configuration(
                format!("cannot write generated SDK declaration: {error}"),
                Some(output_dir.display().to_string()),
            )
        })?;
    }
    let virtual_modules = [
        "/// <reference path=\"../generated/iyon-api.d.ts\" />",
        "/// <reference path=\"../generated/iyon-core.d.ts\" />",
        "/// <reference path=\"../generated/iyon-tui.d.ts\" />",
        "/// <reference path=\"../generated/iyon-plugins.d.ts\" />",
        "",
    ]
    .join("\n");
    std::fs::create_dir_all(output_dir.join("../src")).map_err(|error| {
        ApiSurfaceError::configuration(
            format!("cannot create SDK source directory: {error}"),
            Some(output_dir.display().to_string()),
        )
    })?;
    std::fs::write(
        output_dir.join("../src/virtual-modules.d.ts"),
        virtual_modules,
    )
    .map_err(|error| {
        ApiSurfaceError::configuration(
            format!("cannot write SDK virtual-module declarations: {error}"),
            Some(output_dir.display().to_string()),
        )
    })?;
    Ok(())
}

fn item_kinds(manifest: &ApiManifest) -> BTreeMap<String, ApiKind> {
    manifest
        .crates
        .iter()
        .flat_map(|package| {
            package
                .surface
                .items
                .iter()
                .map(|item| (item.id.0.clone(), item.kind.clone()))
        })
        .collect()
}

fn render_module(
    module: &str,
    records: Vec<&BindingRecord>,
    kinds: &BTreeMap<String, ApiKind>,
) -> String {
    let mut used = BTreeSet::new();
    let mut output = format!(
        "// Generated by api-surface schema 1; runtime implementation is owned by later tranches.\ndeclare module \"{module}\" {{\n"
    );
    for record in records {
        let export = unique_export(&record.typescript_export, &mut used);
        let kind = kinds
            .get(&record.item_id)
            .cloned()
            .unwrap_or(ApiKind::TypeAlias);
        output.push_str(&format!(
            "  // {} [{} / {}]\n",
            record.path,
            strategy_name(&record.strategy),
            record.implementation_owner
        ));
        output.push_str(&format!(
            "  {}\n",
            declaration(&export, &record.strategy, &kind)
        ));
    }
    output.push_str("}\n");
    output
}

fn declaration(export: &str, strategy: &Strategy, kind: &ApiKind) -> String {
    match strategy {
        Strategy::NativeAsync => {
            format!("export function {export}(...args: readonly unknown[]): Promise<unknown>;")
        }
        Strategy::NativeSync => {
            format!("export function {export}(...args: readonly unknown[]): unknown;")
        }
        Strategy::TraitAdapter => format!("export interface {export} {{}}"),
        Strategy::NativeHandle => {
            format!("export interface {export} {{ readonly __nativeHandle: unique symbol; }}")
        }
        Strategy::MirrorValue | Strategy::LazyValue => format!(
            "export type {export} = {value_type};",
            value_type = value_type(kind)
        ),
        Strategy::TsFacade | Strategy::CompatibilityProjection => {
            format!("export type {export} = unknown;")
        }
    }
}

fn value_type(kind: &ApiKind) -> &'static str {
    match kind {
        ApiKind::Function | ApiKind::Method | ApiKind::AssociatedFunction => {
            "(...args: readonly unknown[]) => unknown"
        }
        ApiKind::Const | ApiKind::Static | ApiKind::AssociatedConst => "unknown",
        _ => "Record<string, unknown>",
    }
}

fn unique_export(export: &str, used: &mut BTreeSet<String>) -> String {
    if used.insert(export.to_owned()) {
        return export.to_owned();
    }
    let mut index = 2;
    loop {
        let candidate = format!("{export}_{index}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
        index += 1;
    }
}

fn strategy_name(strategy: &Strategy) -> &'static str {
    match strategy {
        Strategy::MirrorValue => "MirrorValue",
        Strategy::LazyValue => "LazyValue",
        Strategy::NativeHandle => "NativeHandle",
        Strategy::NativeSync => "NativeSync",
        Strategy::NativeAsync => "NativeAsync",
        Strategy::TraitAdapter => "TraitAdapter",
        Strategy::TsFacade => "TsFacade",
        Strategy::CompatibilityProjection => "CompatibilityProjection",
    }
}

fn plugins_stub() -> String {
    "// Generated declaration stub; plugin lifecycle is owned by T6.\ndeclare module \"iyon:plugins\" {\n  export interface PluginContext { readonly kind: \"iyon:plugins\"; }\n  export type Contribution = Record<string, unknown>;\n}\n".into()
}
