[package]
name = "iyon-tui"
version.workspace = true
edition.workspace = true

[features]
test-util = []

[dependencies]
anyhow.workspace = true
termwiz.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
unicode-linebreak.workspace = true
tokio.workspace = true
textwrap = "0.16.2"
pulldown-cmark.workspace = true

[dev-dependencies]
vt100.workspace = true
proptest.workspace = true
insta.workspace = true
trybuild.workspace = true
