[package]
name = "iyon-core-native"
license = "MIT"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
iyon-api.workspace = true
iyon-core.workspace = true
keyring.workspace = true
napi.workspace = true
napi-derive.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
futures-util.workspace = true

[build-dependencies]
napi-build = "2.4.1"
